### ISSUE TITLE
KeyError91

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hutuqiu/bseqc#2]
```
What steps will reproduce the problem?
1. bseqc mbias -s <samfile> -r <reference genome> -g <effective genome size>
2.
3.

What is the expected output? What do you see instead?
I expect the program to run to completion.I use a sam file that is 30gb in 
size. It runs for a few hours and later throws a key error


What version of the product are you using? On what operating system?
bseqc 1.0.3 on Unix

Please provide any additional information below.


```

Original issue reported on code.google.com by `vinodh.r...@gmail.com` on 1 Sep 2014 at 1:17

Attachments:
* [nohup.out](https://storage.googleapis.com/google-code-attachments/bseqc/issue-2/comment-0/nohup.out)

**Comment by divy-kangeyan** [comment]
I am getting similar keyError:94. Although the issue has been closed there is no clear solution stated in the issue, so I would like to reopen it.
